channels:
- conda-forge
dependencies:
- python=3.8.11
- pip
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - psutil==5.8.0
  - scikit-learn==0.0
  - scikit-learn==0.24.2
  - typing-extensions==3.10.0.0
name: mlflow-env
