name: Cyberbullying Detection

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build,Push and release a docker container to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with: 
      
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        dockerfile_directo: ./
        dockerfile_name: DockerFile
        docker_options: "--no-cache"
        process_type: web